/**
 * Copyright (c) 2012 - 2017 by NirvanaXP, LLC. All Rights reserved. Express
 * written consent required to use, copy, share, alter, distribute or transmit
 * this source code in part or whole through any means physical or electronic.
 **/
package com.nirvanaxp.types.entities.discounts;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

import com.nirvanaxp.types.entities.POSNirvanaBaseClass;
import com.nirvanaxp.types.entities.POSNirvanaBaseClassWithBigIntWithGeneratedId;
import com.nirvanaxp.types.entities.POSNirvanaBaseClassWithoutGeneratedIds;
import com.nirvanaxp.types.entities.locations.Location;

/**
 * The persistent class for the discounts database table.
 * 
 */
@Entity
@Table(name = "discounts")
@XmlRootElement(name = "discounts")
public class Discount extends POSNirvanaBaseClassWithoutGeneratedIds{
	public String getGlobalId() {
		 if(globalId != null && (globalId.length()==0 || globalId.equals("0"))){return null;}else{	return globalId;}
	}

	public void setGlobalId(String globalId) {
		this.globalId = globalId;
	}

	public List<Location> getLocationList() {
		return locationList;
	}

	public void setLocationList(List<Location> locationList) {
		this.locationList = locationList;
	}

	private static final long serialVersionUID = 1L;

	@Column(length = 25)
	private String code;

	@Column(length = 1000)
	private String comments;

	@Lob
	private String description;

	@Column(name = "discounts_type_id", nullable = false)
	private String discountsTypeId;

	@Column(name = "discounts_value", nullable = false, precision = 10, scale = 2)
	private BigDecimal discountsValue;

	@Column(name = "display_name", length = 64)
	private String displayName;

	@Column(name = "display_sequence")
	private int displaySequence;

	@Temporal(TemporalType.DATE)
	@Column(name = "effective_end_date", nullable = false)
	private Date effectiveEndDate;

	@Temporal(TemporalType.DATE)
	@Column(name = "effective_start_date", nullable = false)
	private Date effectiveStartDate;

	@Column(name = "is_active", nullable = false, length = 1)
	private int isActive;

	@Column(name = "is_featured", nullable = false, length = 1)
	private int isFeatured;

	@Column(name = "locations_id")
	private String locationsId;

	@Column(nullable = false, length = 50)
	private String name;

	@Column(name = "short_description", nullable = false, length = 100)
	private String shortDescription;

	@Column(name = "is_group")
	private int isGroup;

	@Column(name = "global_id")
	private String globalId;

	@Column(name = "is_coupan")
	private int isCoupan;

	@Column(name = "is_auto_generated")
	private int isAutoGenerated;

	@Column(name = "coupan_code")
	private String coupanCode;

	@Column(name = "min_order_amount")
	private BigDecimal minOrderAmount;

	@Column(name = "is_scan_code")
	private int isScanCode;

	@Column(name = "email_template_id")
	private int emailTemplateId;

	@Column(name = "sms_template_id")
	private int smsTemplateId;

	@Column(name = "number_of_time_discount_used")
	private int numberOfTimeDiscountUsed;

	@Column(name = "is_all_customer")
	private int isAllCustomer;

	private transient List<DiscountToReasons> discountToReasonsList;

	public int getIsAllCustomer() {
		return isAllCustomer;
	}

	public void setIsAllCustomer(int isAllCustomer) {
		this.isAllCustomer = isAllCustomer;
	}

	private transient List<Location> locationList;

	private transient BigDecimal calculatedDiscountValue;

	public BigDecimal getCalculatedDiscountValue() {
		return calculatedDiscountValue;
	}

	public void setCalculatedDiscountValue(BigDecimal calculatedDiscountValue) {
		this.calculatedDiscountValue = calculatedDiscountValue;
	}

	public Discount() {
	}

	public int getNumberOfTimeDiscountUsed() {
		return numberOfTimeDiscountUsed;
	}

	public void setNumberOfTimeDiscountUsed(int numberOfTimeDiscountUsed) {
		this.numberOfTimeDiscountUsed = numberOfTimeDiscountUsed;
	}

	public String getCode() {
		return this.code;
	}

	public int getIsScanCode() {
		return isScanCode;
	}

	public void setIsScanCode(int isScanCode) {
		this.isScanCode = isScanCode;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDiscountsTypeId() {
		 if(discountsTypeId != null && (discountsTypeId.length()==0 || discountsTypeId.equals("0"))){return null;}else{	return discountsTypeId;}
	}

	public void setDiscountsTypeId(String discountsTypeId) {
		this.discountsTypeId = discountsTypeId;
	}

	public BigDecimal getDiscountsValue() {
		return this.discountsValue;
	}

	public void setDiscountsValue(BigDecimal discountsValue) {
		this.discountsValue = discountsValue;
	}

	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public int getDisplaySequence() {
		return this.displaySequence;
	}

	public void setDisplaySequence(int displaySequence) {
		this.displaySequence = displaySequence;
	}

	public Date getEffectiveEndDate() {
		return this.effectiveEndDate;
	}

	public void setEffectiveEndDate(Date effectiveEndDate) {
		this.effectiveEndDate = effectiveEndDate;
	}

	public Date getEffectiveStartDate() {
		return this.effectiveStartDate;
	}

	public void setEffectiveStartDate(Date effectiveStartDate) {
		this.effectiveStartDate = effectiveStartDate;
	}

	public int getIsActive() {
		return this.isActive;
	}

	public void setIsActive(int isActive) {
		this.isActive = isActive;
	}

	public int getIsFeatured() {
		return this.isFeatured;
	}

	public void setIsFeatured(int isFeatured) {
		this.isFeatured = isFeatured;
	}

	public String getLocationsId() {
		if(locationsId != null && (locationsId.length()==0 || locationsId.equals("0"))){return null;}else{	if(locationsId != null && (locationsId.length()==0 || locationsId.equals("0"))){return null;}else{	return locationsId;}}
	}

	public void setLocationsId(String locationsId) {
		this.locationsId = locationsId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getShortDescription() {
		return this.shortDescription;
	}

	public void setShortDescription(String shortDescription) {
		this.shortDescription = shortDescription;
	}

	/**
	 * @return the isGroup
	 */
	public int getIsGroup() {
		return isGroup;
	}

	/**
	 * @param isGroup
	 *            the isGroup to set
	 */
	public void setIsGroup(int isGroup) {
		this.isGroup = isGroup;
	}

	public List<DiscountToReasons> getDiscountToReasonsList() {
		return discountToReasonsList;
	}

	public void setDiscountToReasonsList(List<DiscountToReasons> discountToReasonsList) {
		this.discountToReasonsList = discountToReasonsList;
	}

	public int getIsCoupan() {
		return isCoupan;
	}

	public int getIsAutoGenerated() {
		return isAutoGenerated;
	}

	public String getCoupanCode() {
		return coupanCode;
	}

	public void setIsCoupan(int isCoupan) {
		this.isCoupan = isCoupan;
	}

	public void setIsAutoGenerated(int isAutoGenerated) {
		this.isAutoGenerated = isAutoGenerated;
	}

	public void setCoupanCode(String coupanCode) {
		this.coupanCode = coupanCode;
	}

	public BigDecimal getMinOrderAmount() {
		return minOrderAmount;
	}

	public void setMinOrderAmount(BigDecimal minOrderAmount) {
		this.minOrderAmount = minOrderAmount;
	}

	public int getEmailTemplateId() {
		return emailTemplateId;
	}

	public void setEmailTemplateId(int emailTemplateId) {
		this.emailTemplateId = emailTemplateId;
	}

	@Override
	public String toString() {
		return "Discount [code=" + code + ", comments=" + comments + ", description=" + description
				+ ", discountsTypeId=" + discountsTypeId + ", discountsValue=" + discountsValue + ", displayName="
				+ displayName + ", displaySequence=" + displaySequence + ", effectiveEndDate=" + effectiveEndDate
				+ ", effectiveStartDate=" + effectiveStartDate + ", isActive=" + isActive + ", isFeatured=" + isFeatured
				+ ", locationsId=" + locationsId + ", name=" + name + ", shortDescription=" + shortDescription
				+ ", isGroup=" + isGroup + ", globalId=" + globalId + ", isCoupan=" + isCoupan + ", isAutoGenerated="
				+ isAutoGenerated + ", coupanCode=" + coupanCode + ", minOrderAmount=" + minOrderAmount
				+ ", isScanCode=" + isScanCode + ", emailTemplateId=" + emailTemplateId + ", smsTemplateId="
				+ smsTemplateId + ", numberOfTimeDiscountUsed=" + numberOfTimeDiscountUsed + ", isAllCustomer="
				+ isAllCustomer + "]";
	}

	public int getSmsTemplateId() {
		return smsTemplateId;
	}

	public void setSmsTemplateId(int smsTemplateId) {
		this.smsTemplateId = smsTemplateId;
	}

	public Discount getDiscount(Discount dis) {
		Discount d = new Discount();
		d.setCode(dis.getCode());
		d.setComments(dis.getComments());
		d.setCreated(dis.getCreated());
		d.setCreatedBy(dis.getCreatedBy());
		d.setDescription(dis.getDescription());
		d.setDiscountsTypeId(dis.getDiscountsTypeId());
		d.setDiscountsValue(dis.getDiscountsValue());
		d.setDisplayName(dis.getDisplayName());
		d.setDisplaySequence(dis.getDisplaySequence());
		d.setEffectiveEndDate(dis.getEffectiveEndDate());
		d.setEffectiveStartDate(dis.getEffectiveStartDate());
		d.setGlobalId(dis.getGlobalId());
		d.setIsActive(dis.getIsActive());
		d.setIsFeatured(dis.getIsFeatured());
		d.setIsGroup(dis.getIsGroup());
		d.setLocationList(dis.getLocationList());
		d.setLocationsId(dis.getLocationsId());
		d.setName(dis.getName());
		d.setShortDescription(dis.getShortDescription());
		d.setStatus(dis.getStatus());
		d.setUpdated(dis.getUpdated());
		d.setUpdatedBy(dis.getUpdatedBy());
		d.setIsCoupan(dis.getIsCoupan());
		d.setIsAutoGenerated(dis.getIsAutoGenerated());
		d.setCoupanCode(dis.getCoupanCode());
		d.setMinOrderAmount(dis.getMinOrderAmount());
		d.setIsScanCode(dis.getIsScanCode());
		d.setEmailTemplateId(dis.getEmailTemplateId());
		d.setSmsTemplateId(dis.getSmsTemplateId());
		d.setIsAllCustomer(dis.getIsAllCustomer());
		d.setNumberOfTimeDiscountUsed(dis.getNumberOfTimeDiscountUsed());

		return d;
	}
}