package com.nirvanaxp.types.entities.orders;

import com.nirvanaxp.types.entities.payment.PaymentMethod;
import com.nirvanaxp.types.entities.payment.PaymentTransactionType;
import com.nirvanaxp.types.entities.payment.TransactionStatus;
import java.math.BigDecimal;
import java.util.Date;
import javax.annotation.Generated;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@Generated(value="Dali", date="2019-04-25T12:09:36.687+0530")
@StaticMetamodel(OrderPaymentDetail.class)
public class OrderPaymentDetail_ {
	public static volatile SingularAttribute<OrderPaymentDetail, String> id;
	public static volatile SingularAttribute<OrderPaymentDetail, BigDecimal> amountPaid;
	public static volatile SingularAttribute<OrderPaymentDetail, BigDecimal> authAmount;
	public static volatile SingularAttribute<OrderPaymentDetail, String> authCode;
	public static volatile SingularAttribute<OrderPaymentDetail, String> avsResponse;
	public static volatile SingularAttribute<OrderPaymentDetail, BigDecimal> balanceDue;
	public static volatile SingularAttribute<OrderPaymentDetail, Integer> batchNumber;
	public static volatile SingularAttribute<OrderPaymentDetail, String> cardNumber;
	public static volatile SingularAttribute<OrderPaymentDetail, String> comments;
	public static volatile SingularAttribute<OrderPaymentDetail, Date> created;
	public static volatile SingularAttribute<OrderPaymentDetail, String> createdBy;
	public static volatile SingularAttribute<OrderPaymentDetail, String> cvMessage;
	public static volatile SingularAttribute<OrderPaymentDetail, String> cvResult;
	public static volatile SingularAttribute<OrderPaymentDetail, String> date;
	public static volatile SingularAttribute<OrderPaymentDetail, String> expiryMonth;
	public static volatile SingularAttribute<OrderPaymentDetail, String> expiryYear;
	public static volatile SingularAttribute<OrderPaymentDetail, Integer> hostRef;
	public static volatile SingularAttribute<OrderPaymentDetail, String> message;
	public static volatile SingularAttribute<OrderPaymentDetail, String> pnRef;
	public static volatile SingularAttribute<OrderPaymentDetail, String> posEntry;
	public static volatile SingularAttribute<OrderPaymentDetail, String> register;
	public static volatile SingularAttribute<OrderPaymentDetail, String> result;
	public static volatile SingularAttribute<OrderPaymentDetail, String> seatId;
	public static volatile SingularAttribute<OrderPaymentDetail, String> securityCode;
	public static volatile SingularAttribute<OrderPaymentDetail, BigDecimal> settledAmount;
	public static volatile SingularAttribute<OrderPaymentDetail, String> time;
	public static volatile SingularAttribute<OrderPaymentDetail, BigDecimal> tipAmount;
	public static volatile SingularAttribute<OrderPaymentDetail, BigDecimal> totalAmount;
	public static volatile SingularAttribute<OrderPaymentDetail, Date> updated;
	public static volatile SingularAttribute<OrderPaymentDetail, String> updatedBy;
	public static volatile SingularAttribute<OrderPaymentDetail, String> orderHeaderId;
	public static volatile SingularAttribute<OrderPaymentDetail, PaymentMethod> paymentMethod;
	public static volatile SingularAttribute<OrderPaymentDetail, PaymentTransactionType> paymentTransactionType;
	public static volatile SingularAttribute<OrderPaymentDetail, Integer> isRefunded;
	public static volatile SingularAttribute<OrderPaymentDetail, String> signatureUrl;
	public static volatile SingularAttribute<OrderPaymentDetail, BigDecimal> changeDue;
	public static volatile SingularAttribute<OrderPaymentDetail, TransactionStatus> transactionStatus;
	public static volatile SingularAttribute<OrderPaymentDetail, BigDecimal> cashTipAmt;
	public static volatile SingularAttribute<OrderPaymentDetail, BigDecimal> creditcardTipAmt;
	public static volatile SingularAttribute<OrderPaymentDetail, Integer> payementGatewayId;
	public static volatile SingularAttribute<OrderPaymentDetail, String> cardType;
	public static volatile SingularAttribute<OrderPaymentDetail, String> acqRefData;
	public static volatile SingularAttribute<OrderPaymentDetail, String> hostRefStr;
	public static volatile SingularAttribute<OrderPaymentDetail, String> invoiceNumber;
	public static volatile SingularAttribute<OrderPaymentDetail, String> nirvanaXpBatchNumber;
	public static volatile SingularAttribute<OrderPaymentDetail, Integer> orderSourceGroupToPaymentGatewayTypeId;
	public static volatile SingularAttribute<OrderPaymentDetail, Integer> orderSourceToPaymentGatewayTypeId;
	public static volatile SingularAttribute<OrderPaymentDetail, String> discountsName;
	public static volatile SingularAttribute<OrderPaymentDetail, String> discountId;
	public static volatile SingularAttribute<OrderPaymentDetail, BigDecimal> discountsValue;
	public static volatile SingularAttribute<OrderPaymentDetail, BigDecimal> calculatedDiscountValue;
	public static volatile SingularAttribute<OrderPaymentDetail, BigDecimal> priceDiscount;
	public static volatile SingularAttribute<OrderPaymentDetail, BigDecimal> priceTax1;
	public static volatile SingularAttribute<OrderPaymentDetail, BigDecimal> priceTax2;
	public static volatile SingularAttribute<OrderPaymentDetail, BigDecimal> priceTax3;
	public static volatile SingularAttribute<OrderPaymentDetail, BigDecimal> priceTax4;
	public static volatile SingularAttribute<OrderPaymentDetail, String> taxName1;
	public static volatile SingularAttribute<OrderPaymentDetail, String> taxName2;
	public static volatile SingularAttribute<OrderPaymentDetail, String> taxName3;
	public static volatile SingularAttribute<OrderPaymentDetail, String> taxName4;
	public static volatile SingularAttribute<OrderPaymentDetail, String> taxDisplayName1;
	public static volatile SingularAttribute<OrderPaymentDetail, String> taxDisplayName2;
	public static volatile SingularAttribute<OrderPaymentDetail, String> taxDisplayName3;
	public static volatile SingularAttribute<OrderPaymentDetail, String> taxDisplayName4;
	public static volatile SingularAttribute<OrderPaymentDetail, BigDecimal> taxRate1;
	public static volatile SingularAttribute<OrderPaymentDetail, BigDecimal> taxRate2;
	public static volatile SingularAttribute<OrderPaymentDetail, BigDecimal> taxRate3;
	public static volatile SingularAttribute<OrderPaymentDetail, BigDecimal> taxRate4;
	public static volatile SingularAttribute<OrderPaymentDetail, BigDecimal> priceGratuity;
	public static volatile SingularAttribute<OrderPaymentDetail, BigDecimal> gratuity;
	public static volatile SingularAttribute<OrderPaymentDetail, String> processData;
	public static volatile SingularAttribute<OrderPaymentDetail, String> sequenceNo;
	public static volatile SingularAttribute<OrderPaymentDetail, BigDecimal> creditTermTip;
	public static volatile SingularAttribute<OrderPaymentDetail, String> deviceToPinPadId;
	public static volatile SingularAttribute<OrderPaymentDetail, String> discountCode;
	public static volatile SingularAttribute<OrderPaymentDetail, String> localTime;
	public static volatile SingularAttribute<OrderPaymentDetail, String> customerFirstName;
	public static volatile SingularAttribute<OrderPaymentDetail, String> customerLastName;
	public static volatile SingularAttribute<OrderPaymentDetail, String> accountNumber;
	public static volatile SingularAttribute<OrderPaymentDetail, String> chequeNumber;
	public static volatile SingularAttribute<OrderPaymentDetail, String> bankName;
	public static volatile SingularAttribute<OrderPaymentDetail, String> opdId;
	public static volatile SingularAttribute<OrderPaymentDetail, BigDecimal> chequeTip;
}
