package com.nirvanaxp.types.entities.orders;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;
import javax.annotation.Generated;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@Generated(value="Dali", date="2019-11-21T10:55:32.267+0530")
@StaticMetamodel(OrderDetailItem.class)
public class OrderDetailItem_ {
	public static volatile SingularAttribute<OrderDetailItem, String> id;
	public static volatile SingularAttribute<OrderDetailItem, BigDecimal> amountPaid;
	public static volatile SingularAttribute<OrderDetailItem, BigDecimal> balanceDue;
	public static volatile SingularAttribute<OrderDetailItem, Date> created;
	public static volatile SingularAttribute<OrderDetailItem, String> createdBy;
	public static volatile SingularAttribute<OrderDetailItem, String> discountId;
	public static volatile SingularAttribute<OrderDetailItem, BigDecimal> gratuity;
	public static volatile SingularAttribute<OrderDetailItem, String> itemsId;
	public static volatile SingularAttribute<OrderDetailItem, BigDecimal> itemsQty;
	public static volatile SingularAttribute<OrderDetailItem, String> itemsShortName;
	public static volatile SingularAttribute<OrderDetailItem, Integer> orderDetailStatusId;
	public static volatile SingularAttribute<OrderDetailItem, Integer> pointOfServiceNum;
	public static volatile SingularAttribute<OrderDetailItem, BigDecimal> priceDiscount;
	public static volatile SingularAttribute<OrderDetailItem, BigDecimal> priceExtended;
	public static volatile SingularAttribute<OrderDetailItem, BigDecimal> priceGratuity;
	public static volatile SingularAttribute<OrderDetailItem, BigDecimal> priceMsrp;
	public static volatile SingularAttribute<OrderDetailItem, BigDecimal> priceSelling;
	public static volatile SingularAttribute<OrderDetailItem, BigDecimal> priceTax1;
	public static volatile SingularAttribute<OrderDetailItem, BigDecimal> priceTax2;
	public static volatile SingularAttribute<OrderDetailItem, BigDecimal> priceTax3;
	public static volatile SingularAttribute<OrderDetailItem, BigDecimal> priceTax4;
	public static volatile SingularAttribute<OrderDetailItem, String> seatId;
	public static volatile SingularAttribute<OrderDetailItem, String> sentCourseId;
	public static volatile SingularAttribute<OrderDetailItem, BigDecimal> serviceTax;
	public static volatile SingularAttribute<OrderDetailItem, BigDecimal> subTotal;
	public static volatile SingularAttribute<OrderDetailItem, BigDecimal> total;
	public static volatile SingularAttribute<OrderDetailItem, Date> updated;
	public static volatile SingularAttribute<OrderDetailItem, String> updatedBy;
	public static volatile SingularAttribute<OrderDetailItem, String> orderHeaderId;
	public static volatile SingularAttribute<OrderDetailItem, String> discountReason;
	public static volatile SingularAttribute<OrderDetailItem, String> discountReasonName;
	public static volatile SingularAttribute<OrderDetailItem, String> discountName;
	public static volatile SingularAttribute<OrderDetailItem, String> discountDisplayName;
	public static volatile SingularAttribute<OrderDetailItem, String> discountTypeId;
	public static volatile SingularAttribute<OrderDetailItem, String> discountTypeName;
	public static volatile SingularAttribute<OrderDetailItem, Integer> discountValue;
	public static volatile SingularAttribute<OrderDetailItem, String> taxName1;
	public static volatile SingularAttribute<OrderDetailItem, String> taxName2;
	public static volatile SingularAttribute<OrderDetailItem, String> taxName3;
	public static volatile SingularAttribute<OrderDetailItem, String> taxName4;
	public static volatile SingularAttribute<OrderDetailItem, String> taxDisplayName1;
	public static volatile SingularAttribute<OrderDetailItem, String> taxDisplayName2;
	public static volatile SingularAttribute<OrderDetailItem, String> taxDisplayName3;
	public static volatile SingularAttribute<OrderDetailItem, String> taxDisplayName4;
	public static volatile SingularAttribute<OrderDetailItem, BigDecimal> taxRate1;
	public static volatile SingularAttribute<OrderDetailItem, BigDecimal> taxRate2;
	public static volatile SingularAttribute<OrderDetailItem, BigDecimal> taxRate3;
	public static volatile SingularAttribute<OrderDetailItem, BigDecimal> taxRate4;
	public static volatile SingularAttribute<OrderDetailItem, BigDecimal> totalTax;
	public static volatile SingularAttribute<OrderDetailItem, BigDecimal> roundOffTotal;
	public static volatile SingularAttribute<OrderDetailItem, String> recallReason;
	public static volatile SingularAttribute<OrderDetailItem, String> recallReasonName;
	public static volatile SingularAttribute<OrderDetailItem, String> parentCategoryId;
	public static volatile SingularAttribute<OrderDetailItem, String> rootCategoryId;
	public static volatile SingularAttribute<OrderDetailItem, Integer> isTabOrderItem;
	public static volatile SingularAttribute<OrderDetailItem, Integer> inventoryAccrual;
	public static volatile SingularAttribute<OrderDetailItem, Integer> isInventoryHandled;
	public static volatile SingularAttribute<OrderDetailItem, String> taxExemptId;
	public static volatile SingularAttribute<OrderDetailItem, BigDecimal> calculatedDiscountValue;
	public static volatile SingularAttribute<OrderDetailItem, Integer> discountWaysId;
	public static volatile SingularAttribute<OrderDetailItem, String> plu;
	public static volatile SingularAttribute<OrderDetailItem, String> itemTransferredFrom;
	public static volatile SingularAttribute<OrderDetailItem, BigInteger> orderHeaderToSeatDetailId;
	public static volatile SingularAttribute<OrderDetailItem, String> localTime;
	public static volatile SingularAttribute<OrderDetailItem, String> discountCode;
	public static volatile SingularAttribute<OrderDetailItem, String> poItemRefrenceNumber;
	public static volatile SingularAttribute<OrderDetailItem, BigDecimal> deliveryCharges;
	public static volatile SingularAttribute<OrderDetailItem, BigDecimal> serviceCharges;
	public static volatile SingularAttribute<OrderDetailItem, String> scheduleDateTime;
	public static volatile SingularAttribute<OrderDetailItem, String> driverId;
	public static volatile SingularAttribute<OrderDetailItem, String> reasonDescription;
}
