package com.nirvanaxp.types.entities.orders;

import java.math.BigDecimal;
import java.util.Date;
import javax.annotation.Generated;
import javax.persistence.metamodel.SetAttribute;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@Generated(value="Dali", date="2019-04-25T14:01:31.525+0530")
@StaticMetamodel(OrderHeaderHistory.class)
public class OrderHeaderHistory_ {
	public static volatile SingularAttribute<OrderHeaderHistory, Integer> id;
	public static volatile SingularAttribute<OrderHeaderHistory, String> addressBillingId;
	public static volatile SingularAttribute<OrderHeaderHistory, String> addressShippingId;
	public static volatile SingularAttribute<OrderHeaderHistory, BigDecimal> amountPaid;
	public static volatile SingularAttribute<OrderHeaderHistory, BigDecimal> balanceDue;
	public static volatile SingularAttribute<OrderHeaderHistory, Date> created;
	public static volatile SingularAttribute<OrderHeaderHistory, String> createdBy;
	public static volatile SingularAttribute<OrderHeaderHistory, String> discountsId;
	public static volatile SingularAttribute<OrderHeaderHistory, String> discountsName;
	public static volatile SingularAttribute<OrderHeaderHistory, String> discountsTypeId;
	public static volatile SingularAttribute<OrderHeaderHistory, String> discountsTypeName;
	public static volatile SingularAttribute<OrderHeaderHistory, BigDecimal> discountsValue;
	public static volatile SingularAttribute<OrderHeaderHistory, BigDecimal> gratuity;
	public static volatile SingularAttribute<OrderHeaderHistory, String> ipAddress;
	public static volatile SingularAttribute<OrderHeaderHistory, String> locationsId;
	public static volatile SingularAttribute<OrderHeaderHistory, String> orderHeaderId;
	public static volatile SingularAttribute<OrderHeaderHistory, String> orderSourceId;
	public static volatile SingularAttribute<OrderHeaderHistory, String> orderStatusId;
	public static volatile SingularAttribute<OrderHeaderHistory, Integer> pointOfServiceCount;
	public static volatile SingularAttribute<OrderHeaderHistory, BigDecimal> priceDiscount;
	public static volatile SingularAttribute<OrderHeaderHistory, BigDecimal> priceExtended;
	public static volatile SingularAttribute<OrderHeaderHistory, BigDecimal> priceGratuity;
	public static volatile SingularAttribute<OrderHeaderHistory, BigDecimal> priceTax1;
	public static volatile SingularAttribute<OrderHeaderHistory, BigDecimal> priceTax2;
	public static volatile SingularAttribute<OrderHeaderHistory, BigDecimal> priceTax3;
	public static volatile SingularAttribute<OrderHeaderHistory, BigDecimal> priceTax4;
	public static volatile SingularAttribute<OrderHeaderHistory, String> reservationsId;
	public static volatile SingularAttribute<OrderHeaderHistory, BigDecimal> serviceTax;
	public static volatile SingularAttribute<OrderHeaderHistory, BigDecimal> subTotal;
	public static volatile SingularAttribute<OrderHeaderHistory, BigDecimal> total;
	public static volatile SingularAttribute<OrderHeaderHistory, Date> updated;
	public static volatile SingularAttribute<OrderHeaderHistory, String> updatedBy;
	public static volatile SingularAttribute<OrderHeaderHistory, String> usersId;
	public static volatile SingularAttribute<OrderHeaderHistory, Integer> paymentWaysId;
	public static volatile SingularAttribute<OrderHeaderHistory, Integer> splitCount;
	public static volatile SingularAttribute<OrderHeaderHistory, String> date;
	public static volatile SingularAttribute<OrderHeaderHistory, String> verificationCode;
	public static volatile SingularAttribute<OrderHeaderHistory, String> qrcode;
	public static volatile SingularAttribute<OrderHeaderHistory, Integer> sessionId;
	public static volatile SingularAttribute<OrderHeaderHistory, String> firstName;
	public static volatile SingularAttribute<OrderHeaderHistory, String> lastName;
	public static volatile SingularAttribute<OrderHeaderHistory, String> serverId;
	public static volatile SingularAttribute<OrderHeaderHistory, String> cashierId;
	public static volatile SingularAttribute<OrderHeaderHistory, String> voidReasonId;
	public static volatile SingularAttribute<OrderHeaderHistory, String> taxName1;
	public static volatile SingularAttribute<OrderHeaderHistory, String> taxName2;
	public static volatile SingularAttribute<OrderHeaderHistory, String> taxName3;
	public static volatile SingularAttribute<OrderHeaderHistory, String> taxName4;
	public static volatile SingularAttribute<OrderHeaderHistory, BigDecimal> totalTax;
	public static volatile SingularAttribute<OrderHeaderHistory, String> taxDisplayName1;
	public static volatile SingularAttribute<OrderHeaderHistory, String> taxDisplayName2;
	public static volatile SingularAttribute<OrderHeaderHistory, String> taxDisplayName3;
	public static volatile SingularAttribute<OrderHeaderHistory, String> taxDisplayName4;
	public static volatile SingularAttribute<OrderHeaderHistory, BigDecimal> taxRate1;
	public static volatile SingularAttribute<OrderHeaderHistory, BigDecimal> taxRate2;
	public static volatile SingularAttribute<OrderHeaderHistory, BigDecimal> taxRate3;
	public static volatile SingularAttribute<OrderHeaderHistory, BigDecimal> taxRate4;
	public static volatile SetAttribute<OrderHeaderHistory, OrderDetailItemsHistory> orderDetailItemsHistories;
	public static volatile SingularAttribute<OrderHeaderHistory, String> mergedLocationsId;
	public static volatile SingularAttribute<OrderHeaderHistory, Integer> isGratuityApplied;
	public static volatile SingularAttribute<OrderHeaderHistory, Date> openTime;
	public static volatile SingularAttribute<OrderHeaderHistory, Date> closeTime;
	public static volatile SingularAttribute<OrderHeaderHistory, String> discountDisplayName;
	public static volatile SingularAttribute<OrderHeaderHistory, BigDecimal> roundOffTotal;
	public static volatile SingularAttribute<OrderHeaderHistory, Integer> isTabOrder;
	public static volatile SingularAttribute<OrderHeaderHistory, Integer> isOrderReopened;
	public static volatile SingularAttribute<OrderHeaderHistory, String> servername;
	public static volatile SingularAttribute<OrderHeaderHistory, String> cashierName;
	public static volatile SingularAttribute<OrderHeaderHistory, String> voidReasonName;
	public static volatile SingularAttribute<OrderHeaderHistory, String> scheduleDateTime;
	public static volatile SingularAttribute<OrderHeaderHistory, String> taxExemptId;
	public static volatile SingularAttribute<OrderHeaderHistory, String> nirvanaXpBatchNumber;
	public static volatile SingularAttribute<OrderHeaderHistory, String> orderNumber;
	public static volatile SingularAttribute<OrderHeaderHistory, Integer> isSeatWiseOrder;
	public static volatile SingularAttribute<OrderHeaderHistory, BigDecimal> calculatedDiscountValue;
	public static volatile SingularAttribute<OrderHeaderHistory, Integer> shiftSlotId;
	public static volatile SingularAttribute<OrderHeaderHistory, BigDecimal> priceDiscountItemLevel;
	public static volatile SingularAttribute<OrderHeaderHistory, String> mergeOrderId;
	public static volatile SingularAttribute<OrderHeaderHistory, String> companyName;
	public static volatile SingularAttribute<OrderHeaderHistory, String> taxNo;
	public static volatile SingularAttribute<OrderHeaderHistory, String> taxDisplayName;
	public static volatile SingularAttribute<OrderHeaderHistory, BigDecimal> deliveryCharges;
	public static volatile SingularAttribute<OrderHeaderHistory, BigDecimal> deliveryTax;
	public static volatile SingularAttribute<OrderHeaderHistory, String> deliveryOptionId;
	public static volatile SingularAttribute<OrderHeaderHistory, BigDecimal> serviceCharges;
	public static volatile SingularAttribute<OrderHeaderHistory, String> preassignedServerId;
	public static volatile SingularAttribute<OrderHeaderHistory, String> localTime;
	public static volatile SingularAttribute<OrderHeaderHistory, String> poRefrenceNumber;
	public static volatile SingularAttribute<OrderHeaderHistory, String> requestedLocationId;
	public static volatile SingularAttribute<OrderHeaderHistory, Integer> orderTypeId;
	public static volatile SingularAttribute<OrderHeaderHistory, String> driverId;
	public static volatile SingularAttribute<OrderHeaderHistory, String> startDate;
	public static volatile SingularAttribute<OrderHeaderHistory, String> endDate;
	public static volatile SingularAttribute<OrderHeaderHistory, String> eventName;
	public static volatile SingularAttribute<OrderHeaderHistory, String> transferredOrderId;
}
