package com.nirvanaxp.types.entities.orders;

import com.nirvanaxp.types.entities.address.Address;
import java.math.BigDecimal;
import java.util.Date;
import javax.annotation.Generated;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@Generated(value="Dali", date="2019-06-06T13:08:15.664+0530")
@StaticMetamodel(OrderHeader.class)
public class OrderHeader_ {
	public static volatile SingularAttribute<OrderHeader, String> id;
	public static volatile SingularAttribute<OrderHeader, Address> addressBilling;
	public static volatile SingularAttribute<OrderHeader, Address> addressShipping;
	public static volatile SingularAttribute<OrderHeader, BigDecimal> amountPaid;
	public static volatile SingularAttribute<OrderHeader, BigDecimal> balanceDue;
	public static volatile SingularAttribute<OrderHeader, Date> created;
	public static volatile SingularAttribute<OrderHeader, String> createdBy;
	public static volatile SingularAttribute<OrderHeader, String> discountsId;
	public static volatile SingularAttribute<OrderHeader, String> discountsName;
	public static volatile SingularAttribute<OrderHeader, String> discountDisplayName;
	public static volatile SingularAttribute<OrderHeader, String> discountsTypeId;
	public static volatile SingularAttribute<OrderHeader, String> discountsTypeName;
	public static volatile SingularAttribute<OrderHeader, BigDecimal> discountsValue;
	public static volatile SingularAttribute<OrderHeader, BigDecimal> gratuity;
	public static volatile SingularAttribute<OrderHeader, String> ipAddress;
	public static volatile SingularAttribute<OrderHeader, String> orderSourceId;
	public static volatile SingularAttribute<OrderHeader, String> orderStatusId;
	public static volatile SingularAttribute<OrderHeader, Integer> pointOfServiceCount;
	public static volatile SingularAttribute<OrderHeader, BigDecimal> priceDiscount;
	public static volatile SingularAttribute<OrderHeader, BigDecimal> priceExtended;
	public static volatile SingularAttribute<OrderHeader, BigDecimal> priceGratuity;
	public static volatile SingularAttribute<OrderHeader, BigDecimal> priceTax1;
	public static volatile SingularAttribute<OrderHeader, BigDecimal> priceTax2;
	public static volatile SingularAttribute<OrderHeader, BigDecimal> priceTax3;
	public static volatile SingularAttribute<OrderHeader, BigDecimal> priceTax4;
	public static volatile SingularAttribute<OrderHeader, String> reservationsId;
	public static volatile SingularAttribute<OrderHeader, BigDecimal> serviceTax;
	public static volatile SingularAttribute<OrderHeader, BigDecimal> subTotal;
	public static volatile SingularAttribute<OrderHeader, BigDecimal> total;
	public static volatile SingularAttribute<OrderHeader, Integer> splitCount;
	public static volatile SingularAttribute<OrderHeader, Date> updated;
	public static volatile SingularAttribute<OrderHeader, String> updatedBy;
	public static volatile SingularAttribute<OrderHeader, String> usersId;
	public static volatile SingularAttribute<OrderHeader, String> locationsId;
	public static volatile SingularAttribute<OrderHeader, Integer> paymentWaysId;
	public static volatile SingularAttribute<OrderHeader, String> date;
	public static volatile SingularAttribute<OrderHeader, String> scheduleDateTime;
	public static volatile SingularAttribute<OrderHeader, String> verificationCode;
	public static volatile SingularAttribute<OrderHeader, String> qrcode;
	public static volatile SingularAttribute<OrderHeader, Integer> sessionKey;
	public static volatile SingularAttribute<OrderHeader, String> firstName;
	public static volatile SingularAttribute<OrderHeader, String> lastName;
	public static volatile SingularAttribute<OrderHeader, String> serverId;
	public static volatile SingularAttribute<OrderHeader, String> cashierId;
	public static volatile SingularAttribute<OrderHeader, String> voidReasonId;
	public static volatile SingularAttribute<OrderHeader, String> mergedLocationsId;
	public static volatile SingularAttribute<OrderHeader, Integer> isGratuityApplied;
	public static volatile SingularAttribute<OrderHeader, Date> openTime;
	public static volatile SingularAttribute<OrderHeader, Date> closeTime;
	public static volatile SingularAttribute<OrderHeader, String> taxName1;
	public static volatile SingularAttribute<OrderHeader, String> taxName2;
	public static volatile SingularAttribute<OrderHeader, String> taxName3;
	public static volatile SingularAttribute<OrderHeader, String> taxName4;
	public static volatile SingularAttribute<OrderHeader, String> taxDisplayName1;
	public static volatile SingularAttribute<OrderHeader, String> taxDisplayName2;
	public static volatile SingularAttribute<OrderHeader, String> taxDisplayName3;
	public static volatile SingularAttribute<OrderHeader, String> taxDisplayName4;
	public static volatile SingularAttribute<OrderHeader, BigDecimal> taxRate1;
	public static volatile SingularAttribute<OrderHeader, BigDecimal> taxRate2;
	public static volatile SingularAttribute<OrderHeader, BigDecimal> taxRate3;
	public static volatile SingularAttribute<OrderHeader, BigDecimal> taxRate4;
	public static volatile SingularAttribute<OrderHeader, BigDecimal> totalTax;
	public static volatile SingularAttribute<OrderHeader, BigDecimal> roundOffTotal;
	public static volatile SingularAttribute<OrderHeader, Integer> isTabOrder;
	public static volatile SingularAttribute<OrderHeader, Integer> isOrderReopened;
	public static volatile SingularAttribute<OrderHeader, Integer> shiftSlotId;
	public static volatile SingularAttribute<OrderHeader, BigDecimal> priceDiscountItemLevel;
	public static volatile SingularAttribute<OrderHeader, String> companyName;
	public static volatile SingularAttribute<OrderHeader, String> taxNo;
	public static volatile SingularAttribute<OrderHeader, String> taxDisplayName;
	public static volatile SingularAttribute<OrderHeader, BigDecimal> deliveryCharges;
	public static volatile SingularAttribute<OrderHeader, BigDecimal> serviceCharges;
	public static volatile SingularAttribute<OrderHeader, String> deliveryOptionId;
	public static volatile SingularAttribute<OrderHeader, BigDecimal> deliveryTax;
	public static volatile SingularAttribute<OrderHeader, String> preassignedServerId;
	public static volatile SingularAttribute<OrderHeader, String> requestedLocationId;
	public static volatile SingularAttribute<OrderHeader, Integer> orderTypeId;
	public static volatile SingularAttribute<OrderHeader, String> comment;
	public static volatile SingularAttribute<OrderHeader, String> transferredOrderId;
	public static volatile SingularAttribute<OrderHeader, String> startDate;
	public static volatile SingularAttribute<OrderHeader, String> endDate;
	public static volatile SingularAttribute<OrderHeader, String> eventName;
	public static volatile SingularAttribute<OrderHeader, String> servername;
	public static volatile SingularAttribute<OrderHeader, String> cashierName;
	public static volatile SingularAttribute<OrderHeader, String> voidReasonName;
	public static volatile SingularAttribute<OrderHeader, String> taxExemptId;
	public static volatile SingularAttribute<OrderHeader, String> referenceNumber;
	public static volatile SingularAttribute<OrderHeader, String> nirvanaXpBatchNumber;
	public static volatile SingularAttribute<OrderHeader, String> orderNumber;
	public static volatile SingularAttribute<OrderHeader, Integer> isSeatWiseOrder;
	public static volatile SingularAttribute<OrderHeader, BigDecimal> calculatedDiscountValue;
	public static volatile SingularAttribute<OrderHeader, String> mergeOrderId;
	public static volatile SingularAttribute<OrderHeader, String> localTime;
	public static volatile SingularAttribute<OrderHeader, String> poRefrenceNumber;
	public static volatile SingularAttribute<OrderHeader, String> driverId;
}
