package com.nirvanaxp.types.entities.orders;

import com.nirvanaxp.types.entities.payment.PaymentMethod;
import com.nirvanaxp.types.entities.payment.PaymentTransactionType;
import com.nirvanaxp.types.entities.payment.TransactionStatus;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;
import javax.annotation.Generated;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@Generated(value="Dali", date="2019-04-25T12:19:43.365+0530")
@StaticMetamodel(OrderPaymentDetailHistory.class)
public class OrderPaymentDetailHistory_ {
	public static volatile SingularAttribute<OrderPaymentDetailHistory, BigInteger> id;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, BigDecimal> amountPaid;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, BigDecimal> authAmount;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> authCode;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> orderPaymentDetailsId;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> avsResponse;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, BigDecimal> balanceDue;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, Integer> batchNumber;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> cardNumber;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> comments;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, Date> created;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> createdBy;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> cvMessage;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> cvResult;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> date;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> expiryMonth;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> expiryYear;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, Integer> hostRef;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> message;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> pnRef;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> posEntry;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> register;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> result;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> seatId;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> securityCode;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, BigDecimal> settledAmount;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> time;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, BigDecimal> tipAmount;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, BigDecimal> totalAmount;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, Date> updated;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> updatedBy;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> orderHeaderId;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, PaymentMethod> paymentMethod;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, PaymentTransactionType> paymentTransactionType;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, Integer> isRefunded;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> signatureUrl;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, BigDecimal> changeDue;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, TransactionStatus> transactionStatus;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, BigDecimal> cashTipAmt;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, BigDecimal> creditcardTipAmt;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, Integer> payementGatewayId;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> cardType;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> acqRefData;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> hostRefStr;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> invoiceNumber;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> nirvanaXpBatchNumber;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, Integer> orderSourceGroupToPaymentGatewayTypeId;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, Integer> orderSourceToPaymentGatewayTypeId;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> discountsName;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> discountId;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, BigDecimal> discountsValue;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, BigDecimal> calculatedDiscountValue;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, BigDecimal> priceDiscount;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, BigDecimal> priceTax1;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, BigDecimal> priceTax2;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, BigDecimal> priceTax3;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, BigDecimal> priceTax4;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> taxName1;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> taxName2;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> taxName3;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> taxName4;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> taxDisplayName1;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> taxDisplayName2;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> taxDisplayName3;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> taxDisplayName4;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, BigDecimal> taxRate1;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, BigDecimal> taxRate2;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, BigDecimal> taxRate3;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, BigDecimal> taxRate4;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, BigDecimal> priceGratuity;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, BigDecimal> gratuity;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> processData;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> sequenceNo;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, BigDecimal> creditTermTip;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> discountCode;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> localTime;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> customerFirstName;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> customerLastName;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> accountNumber;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> chequeNumber;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, String> bankName;
	public static volatile SingularAttribute<OrderPaymentDetailHistory, BigDecimal> chequeTip;
}
