package com.nirvanaxp.types.entities.orders;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;
import javax.annotation.Generated;
import javax.persistence.metamodel.SetAttribute;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@Generated(value="Dali", date="2019-04-11T16:35:03.629+0530")
@StaticMetamodel(OrderDetailItemsHistory.class)
public class OrderDetailItemsHistory_ {
	public static volatile SingularAttribute<OrderDetailItemsHistory, BigInteger> id;
	public static volatile SingularAttribute<OrderDetailItemsHistory, BigDecimal> amountPaid;
	public static volatile SingularAttribute<OrderDetailItemsHistory, BigDecimal> balanceDue;
	public static volatile SingularAttribute<OrderDetailItemsHistory, Date> created;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> createdBy;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> orderHeaderId;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> discountId;
	public static volatile SingularAttribute<OrderDetailItemsHistory, BigDecimal> gratuity;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> itemsId;
	public static volatile SingularAttribute<OrderDetailItemsHistory, BigDecimal> itemsQty;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> itemsShortName;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> orderDetailItemsId;
	public static volatile SingularAttribute<OrderDetailItemsHistory, Integer> orderDetailStatusId;
	public static volatile SingularAttribute<OrderDetailItemsHistory, Integer> pointOfServiceNum;
	public static volatile SingularAttribute<OrderDetailItemsHistory, BigDecimal> priceDiscount;
	public static volatile SingularAttribute<OrderDetailItemsHistory, BigDecimal> priceExtended;
	public static volatile SingularAttribute<OrderDetailItemsHistory, BigDecimal> priceGratuity;
	public static volatile SingularAttribute<OrderDetailItemsHistory, BigDecimal> priceMsrp;
	public static volatile SingularAttribute<OrderDetailItemsHistory, BigDecimal> priceSelling;
	public static volatile SingularAttribute<OrderDetailItemsHistory, BigDecimal> priceTax1;
	public static volatile SingularAttribute<OrderDetailItemsHistory, BigDecimal> priceTax2;
	public static volatile SingularAttribute<OrderDetailItemsHistory, BigDecimal> priceTax3;
	public static volatile SingularAttribute<OrderDetailItemsHistory, BigDecimal> priceTax4;
	public static volatile SingularAttribute<OrderDetailItemsHistory, Integer> seatId;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> sentCourseId;
	public static volatile SingularAttribute<OrderDetailItemsHistory, BigDecimal> serviceTax;
	public static volatile SingularAttribute<OrderDetailItemsHistory, BigDecimal> subTotal;
	public static volatile SingularAttribute<OrderDetailItemsHistory, BigDecimal> total;
	public static volatile SingularAttribute<OrderDetailItemsHistory, Date> updated;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> updatedBy;
	public static volatile SetAttribute<OrderDetailItemsHistory, OrderDetailAttributeHistory> orderDetailAttributesHistories;
	public static volatile SingularAttribute<OrderDetailItemsHistory, OrderHeaderHistory> orderHeaderHistories;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> discountReason;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> discountReasonName;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> discountName;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> discountTypeId;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> discountTypeName;
	public static volatile SingularAttribute<OrderDetailItemsHistory, Integer> discountValue;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> discountDisplayName;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> taxName1;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> taxName2;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> taxName3;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> taxName4;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> taxDisplayName1;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> taxDisplayName2;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> taxDisplayName3;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> taxDisplayName4;
	public static volatile SingularAttribute<OrderDetailItemsHistory, BigDecimal> taxRate1;
	public static volatile SingularAttribute<OrderDetailItemsHistory, BigDecimal> taxRate2;
	public static volatile SingularAttribute<OrderDetailItemsHistory, BigDecimal> taxRate3;
	public static volatile SingularAttribute<OrderDetailItemsHistory, BigDecimal> taxRate4;
	public static volatile SingularAttribute<OrderDetailItemsHistory, BigDecimal> totalTax;
	public static volatile SingularAttribute<OrderDetailItemsHistory, BigDecimal> roundOffTotal;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> recallReason;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> recallReasonName;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> parentCategoryId;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> rootCategoryId;
	public static volatile SingularAttribute<OrderDetailItemsHistory, Integer> isTabOrderItem;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> taxExemptId;
	public static volatile SingularAttribute<OrderDetailItemsHistory, BigDecimal> calculatedDiscountValue;
	public static volatile SingularAttribute<OrderDetailItemsHistory, Integer> discountWaysId;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> plu;
	public static volatile SingularAttribute<OrderDetailItemsHistory, BigInteger> orderHeaderToSeatDetailId;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> itemTransferredFrom;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> localTime;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> discountCode;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> poItemRefrenceNumber;
	public static volatile SingularAttribute<OrderDetailItemsHistory, BigDecimal> deliveryCharges;
	public static volatile SingularAttribute<OrderDetailItemsHistory, BigDecimal> serviceCharges;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> scheduleDateTime;
	public static volatile SingularAttribute<OrderDetailItemsHistory, String> driverId;
}
